[package]
name = "th-market-data"
version.workspace = true
edition.workspace = true
[dependencies]
async-trait.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
th-domain={path="../domain"}

[features]
default = []
test-utils = []
