[package]
name="th-execution"
version.workspace=true
edition.workspace=true
[dependencies]
async-trait.workspace=true
chrono.workspace=true
chrono-tz.workspace=true
reqwest.workspace=true
serde.workspace=true
serde_json.workspace=true
thiserror.workspace=true
uuid.workspace=true
tokio.workspace=true
th-domain={path="../domain"}
th-risk={path="../risk"}
sha2.workspace=true
