from pathlib import Path
root=Path(__file__).resolve().parents[1]
hive=(root/'crates/hive/src/lib.rs').read_text()
bot=(root/'crates/bot/src/lib.rs').read_text()
strategy=(root/'crates/strategy/src/lib.rs').read_text()
cli=(root/'crates/cli/src/main.rs').read_text()
ci=(root/'.github/workflows/ci.yml').read_text()
checks=[]
def C(name,ok): checks.append((name,bool(ok)))
C('exactly 30 seeds','ids.into_iter().take(30)' in strategy)
C('120..180 option expiry','m>=policy.min_expiry_minutes' in hive and 'm<=policy.max_expiry_minutes' in hive)
C('Hive quantity isolation','quantity:0' in (root/'crates/deployment/src/lib.rs').read_text())
C('worker quantity from ask','calculate_worker_quantity' in bot and 'quote.ask' in bot)
C('stop loss ENV','TRADING_STOP_LOSS_PCT' in bot)
C('180 minute worker horizon','bot_max_hold_minutes!=180' in bot and 'bot_max_hold_minutes:180' in bot)
C('confidence capital allocation','confidence_allocate' in hive and 'total*c/denom' in hive)
C('RL over seed action set','let actions=registry.seed_ids()' in hive)
C('real reward from next bar','bars[i+1].close/bars[i].close-1.0' in hive)
C('STRAT-31 generated','id:"STRAT-31"' in hive)
C('STRAT-31 validation','validate_generated_strategy' in hive)
C('accepted STRAT-31 promoted','GENERATED_STRATEGY_PASSED_RESEARCH_GATES' in hive)
C('STRAT-31 activation path','create_synthesized(&g.blueprint)' in bot)
C('STRAT-31 manufacturing path','strategy_id=="STRAT-31"' in hive)
C('API option chain','provider.option_chain' in cli)
C('paper smoke','PaperBroker::new' in cli)
C('four hour analysis window','analysis_hours!=4' in bot and 'analysis_hours:20' not in bot)
C('cross platform CI',all(x in ci for x in ['ubuntu-latest','windows-latest','macos-latest']))
for n,ok in checks: print(('PASS' if ok else 'FAIL')+' '+n)
raise SystemExit(1 if not all(ok for _,ok in checks) else 0)
